<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE invoice[

<!ELEMENT invoice (invoiceNumber,store,date,employee,items,total)>
<!ELEMENT invoiceNumber (#PCDATA)>
<!ELEMENT store (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT employee (#PCDATA)>
<!ELEMENT items (item*)>
<!ELEMENT item (description,quantity,amount)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT total (#PCDATA)>
]>
<invoice>
    <invoiceNumber>113654</invoiceNumber>
    <store>Wollongong</store>
    <date>15/06/2021</date>
    <employee>Tim Kim</employee>
    <items>
        <item>
            <description>milk</description>
            <quantity>2</quantity>
            <amount>7.20</amount>
        </item>
        <item>
            <description>Chicken tenders</description>
            <quantity>5</quantity>
            <amount>25.75</amount>
        </item>
        <item>
            <description>Frozen pasta</description>
            <quantity>10</quantity>
            <amount>67.40</amount>
        </item>
    </items>
    <total>100.35</total>
</invoice>
